# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'error_msg.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os,sys

class Error_window(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
    def setupUi(self, error_window):
        error_window.setObjectName("error_window")
        error_window.resize(307, 140)
        self.exe_dir = os.path.dirname(sys.executable) if getattr(sys, 'frozen', False) else os.path.dirname(__file__)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(error_window.sizePolicy().hasHeightForWidth())
        error_window.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(
                  os.path.join(self.exe_dir, "_internal","resource" , "sgLogo.ico")     
                # os.path.join(os.getcwd(), '..',"resource/sgLogo.ico")
                ))
        error_window.setWindowIcon(icon)
        error_window.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(error_window)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(error_window)
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMaximumSize(QtCore.QSize(80, 80))
        self.label.setText("Some error have exists")
        self.label.setPixmap(QtGui.QPixmap(
            # os.path.join(os.getcwd(), "resource/sgLogo.png")
            os.path.join(self.exe_dir, "_internal","resource" , "sgLogo.png")
            ))
        
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.error_msg_lable = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(10)
        self.error_msg_lable.setFont(font)
        self.error_msg_lable.setStyleSheet("color: rgb(239, 41, 41);")
        self.error_msg_lable.setText("")
        self.error_msg_lable.setAlignment(QtCore.Qt.AlignCenter)
        self.error_msg_lable.setObjectName("error_msg_lable")
        self.horizontalLayout.addWidget(self.error_msg_lable)
        self.verticalLayout.addWidget(self.widget)
        self.buttonBox = QtWidgets.QDialogButtonBox(error_window)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(error_window)
        self.buttonBox.accepted.connect(error_window.accept) # type: ignore
        # self.buttonBox.rejected.connect(error_window.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(error_window)

    def retranslateUi(self, error_window):
        _translate = QtCore.QCoreApplication.translate
        error_window.setWindowTitle(_translate("error_window", "Error"))

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     menu = QtWidgets.QDialog()
#     ui = Error_window()
#     ui.setupUi(menu)
#     menu.show()
#     sys.exit(app.exec_())

