# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os,sys

class Login_window(QtWidgets.QDialog):
    # def __init__(self):
    #     super().__init__()
    #     self.setupUi(self)
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1220, 659)
        self.exe_dir = os.path.dirname(sys.executable) if getattr(sys, 'frozen', False) else os.path.dirname(__file__)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(
            # os.path.join(os.getcwd(), "resource/sgLogo.ico")
              os.path.join(self.exe_dir, "_internal", "resource" ,"sgLogo.ico")  
            ))
        Dialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setMinimumSize(QtCore.QSize(300, 0))
        self.widget_2.setObjectName("widget_2")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setGeometry(QtCore.QRect(9, 9, 282, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_3.setObjectName("widget_3")
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        self.label_4.setGeometry(QtCore.QRect(70, 10, 150, 80))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(
            # os.path.join(os.getcwd(), "resource/logo.png")
            os.path.join(self.exe_dir, "_internal", "resource" ,"logo.png")  
            ))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setGeometry(QtCore.QRect(9, 101, 282, 71))
        self.widget_5.setStyleSheet("color: rgb(69, 130, 255);")
        self.widget_5.setObjectName("widget_5")
        self.label_5 = QtWidgets.QLabel(self.widget_5)
        self.label_5.setGeometry(QtCore.QRect(20, 0, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(69, 130, 255);")
        self.label_5.setTextFormat(QtCore.Qt.PlainText)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.email_txt = QtWidgets.QLineEdit(self.widget_2)
        self.email_txt.setGeometry(QtCore.QRect(10, 220, 281, 41))
        self.email_txt.setStyleSheet("")
        self.email_txt.setObjectName("email_txt")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(10, 280, 281, 20))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.password_txt = QtWidgets.QLineEdit(self.widget_2)
        self.password_txt.setGeometry(QtCore.QRect(10, 310, 281, 41))
        self.password_txt.setObjectName("password_txt")
        self.loginbtn = QtWidgets.QPushButton(self.widget_2)
        self.loginbtn.setGeometry(QtCore.QRect(10, 440, 281, 51))
        
        self.loginbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginbtn.setStyleSheet("#loginbtn{\n"
"border-radius:20px;\n"
"    background-color: rgb(238, 238, 236);\n"
"}\n"
"\n"
"#loginbtn:hover {\n"
"     font-size:20px;   \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(69, 130, 255);\n"
"        }")
        self.loginbtn.setObjectName("loginbtn")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(0, 190, 291, 21))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("margin-left:5px;")
        self.label_3.setObjectName("label_3")
        self.error_label = QtWidgets.QLabel(self.widget_2)
        self.error_label.setGeometry(QtCore.QRect(10, 370, 271, 51))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.error_label.setFont(font)
        self.error_label.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.error_label.setStyleSheet("color: rgb(239, 41, 41);")
        self.error_label.setText("")
        self.error_label.setAlignment(QtCore.Qt.AlignCenter)
        self.error_label.setObjectName("error_label")
        self.horizontalLayout.addWidget(self.widget_2)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget_4)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(
            # os.path.join(os.getcwd(),"resource/login2.jpg")
            os.path.join(self.exe_dir, "_internal", "resource" ,"login2.jpg")
            ))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.horizontalLayout.addWidget(self.widget_4)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Login"))
        self.label_5.setText(_translate("Dialog", "Login Here"))
        self.email_txt.setPlaceholderText(_translate("Dialog", "Enter the email"))
        self.label_2.setText(_translate("Dialog", "Password"))
        self.password_txt.setPlaceholderText(_translate("Dialog", "Enter the password"))
        self.password_txt.setEchoMode(QtWidgets.QLineEdit.Password)
        self.loginbtn.setText(_translate("Dialog", "Login"))
        
        self.label_3.setText(_translate("Dialog", "Email "))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Dialog = QtWidgets.QDialog()
#     ui = Login_window()

#     ui.setupUi(Dialog)
#     Dialog.show()
#     sys.exit(app.exec_())
