# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'open_task.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os,sys

class OpenTask(object):
    def setupUi(self, open_task_2):
        open_task_2.setObjectName("open_task_2")
        open_task_2.resize(154, 77)
        self.exe_dir = os.path.dirname(sys.executable) if getattr(sys, 'frozen', False) else os.path.dirname(__file__)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(
            # os.path.join(os.getcwd(), "resource/sgLogo.ico")
            os.path.join(self.exe_dir, "_internal","resource" , "sgLogo.ico")
            ))
        open_task_2.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(open_task_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(open_task_2)
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.open_task_btn = QtWidgets.QPushButton(self.widget)
        self.open_task_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.open_task_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open_task_btn.setStyleSheet("#open_task_btn{border-radius:10px;}\n"
"QPushButton:hover {\n"
"            background-color: rgb(211, 215, 207);\n"
"        }\n"
"")
        self.open_task_btn.setObjectName("open_task_btn")
        self.verticalLayout_2.addWidget(self.open_task_btn)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(open_task_2)
        QtCore.QMetaObject.connectSlotsByName(open_task_2)

    def retranslateUi(self, open_task_2):
        _translate = QtCore.QCoreApplication.translate
        open_task_2.setWindowTitle(_translate("open_task_2", "Open Task"))
        self.open_task_btn.setText(_translate("open_task_2", "Open Task"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     open_task_2 = QtWidgets.QDialog()
#     ui = OpenTask()
#     ui.setupUi(open_task_2)
#     open_task_2.show()
#     sys.exit(app.exec_())
